# Generated by Django 4.0.5 on 2022-10-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Besedka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Besedka's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Besedka's description")),
                ('fire', models.TextField(blank=True, null=True, verbose_name="Fire's description")),
                ('tools', models.TextField(blank=True, null=True, verbose_name='Tools description')),
                ('area', models.TextField(blank=True, null=True, verbose_name="Area's description")),
                ('parking', models.TextField(blank=True, null=True, verbose_name="Parking's description")),
            ],
        ),
    ]
