# Generated by Django 4.0.5 on 2022-10-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billiard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Billiard's name")),
                ('par', models.TextField(blank=True, null=True, verbose_name='Par description')),
                ('water', models.TextField(blank=True, null=True, verbose_name='Water description')),
                ('rest', models.TextField(blank=True, null=True, verbose_name='Rest description')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='Extra description')),
                ('besedka', models.ManyToManyField(related_name='besedkas', to='list.besedka', verbose_name='Besedka')),
            ],
        ),
    ]
